--
-- PostgreSQL database dump
--

-- Dumped from database version 13.4
-- Dumped by pg_dump version 13.4

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

ALTER TABLE IF EXISTS ONLY scheme.room DROP CONSTRAINT IF EXISTS room_fk;
ALTER TABLE IF EXISTS ONLY scheme.apartments DROP CONSTRAINT IF EXISTS appartement_fk;
ALTER TABLE IF EXISTS ONLY scheme.human DROP CONSTRAINT IF EXISTS human_un;
ALTER TABLE IF EXISTS ONLY scheme.human DROP CONSTRAINT IF EXISTS human_pk;
ALTER TABLE IF EXISTS ONLY scheme.apartments DROP CONSTRAINT IF EXISTS appartement_pk;
ALTER TABLE IF EXISTS ONLY public.tasks DROP CONSTRAINT IF EXISTS tasks_pkey;
ALTER TABLE IF EXISTS ONLY scheme.apartments DROP CONSTRAINT IF EXISTS appartement_un;
DROP TABLE IF EXISTS scheme.room;
DROP TABLE IF EXISTS scheme.human;
DROP TABLE IF EXISTS scheme.apartments;
DROP TABLE IF EXISTS public.tasks;
DROP SCHEMA IF EXISTS scheme;
--
-- Name: scheme; Type: SCHEMA; Schema: -; Owner: postgres
--

CREATE SCHEMA scheme;


ALTER SCHEMA scheme OWNER TO postgres;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: tasks; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.tasks (
    id bigint NOT NULL,
    title text NOT NULL,
    priority integer NOT NULL
);


ALTER TABLE public.tasks OWNER TO postgres;

--
-- Name: tasks_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.tasks ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tasks_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: apartments; Type: TABLE; Schema: scheme; Owner: postgres
--

CREATE TABLE scheme.apartments (
    id integer,
    location character varying(24),
    apartment_id integer NOT NULL
);


ALTER TABLE scheme.apartments OWNER TO postgres;

--
-- Name: human; Type: TABLE; Schema: scheme; Owner: postgres
--

CREATE TABLE scheme.human (
    id integer NOT NULL,
    name character varying(24),
    phone character varying(24)
);


ALTER TABLE scheme.human OWNER TO postgres;

--
-- Name: room; Type: TABLE; Schema: scheme; Owner: postgres
--

CREATE TABLE scheme.room (
    apartment_id integer,
    color character varying(24)
);


ALTER TABLE scheme.room OWNER TO postgres;

--
-- Data for Name: tasks; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- Data for Name: apartments; Type: TABLE DATA; Schema: scheme; Owner: postgres
--

INSERT INTO scheme.apartments (id, location, apartment_id) VALUES (1, 'Moscow', 34);
INSERT INTO scheme.apartments (id, location, apartment_id) VALUES (2, 'Kazan', 23);
INSERT INTO scheme.apartments (id, location, apartment_id) VALUES (4, 'Tver', 98);
INSERT INTO scheme.apartments (id, location, apartment_id) VALUES (5, 'Tula', 45);
INSERT INTO scheme.apartments (id, location, apartment_id) VALUES (2, 'Krasnodar', 74);
INSERT INTO scheme.apartments (id, location, apartment_id) VALUES (2, 'Kursk', 2);
INSERT INTO scheme.apartments (id, location, apartment_id) VALUES (4, 'Ufa', 38);
INSERT INTO scheme.apartments (id, location, apartment_id) VALUES (1, 'Tumen', 19);
INSERT INTO scheme.apartments (id, location, apartment_id) VALUES (3, 'Tver', 1);


--
-- Data for Name: human; Type: TABLE DATA; Schema: scheme; Owner: postgres
--

INSERT INTO scheme.human (id, name, phone) VALUES (1, 'Regina', '2394290');
INSERT INTO scheme.human (id, name, phone) VALUES (2, 'Egor', '9283918');
INSERT INTO scheme.human (id, name, phone) VALUES (3, 'Sofia', '9122829');
INSERT INTO scheme.human (id, name, phone) VALUES (4, 'Vlad', '1255523');
INSERT INTO scheme.human (id, name, phone) VALUES (5, 'Max', '2341231');
INSERT INTO scheme.human (id, name, phone) VALUES (6, 'Andrew', '7827818');
INSERT INTO scheme.human (id, name, phone) VALUES (7, 'Timur', '9218192');


--
-- Data for Name: room; Type: TABLE DATA; Schema: scheme; Owner: postgres
--

INSERT INTO scheme.room (apartment_id, color) VALUES (34, 'Black');
INSERT INTO scheme.room (apartment_id, color) VALUES (23, 'Yellow');
INSERT INTO scheme.room (apartment_id, color) VALUES (1, 'Chrome');
INSERT INTO scheme.room (apartment_id, color) VALUES (74, 'Lavender');
INSERT INTO scheme.room (apartment_id, color) VALUES (1, 'Lime');
INSERT INTO scheme.room (apartment_id, color) VALUES (23, 'Teal');
INSERT INTO scheme.room (apartment_id, color) VALUES (1, 'Maroon');
INSERT INTO scheme.room (apartment_id, color) VALUES (34, 'Plum');
INSERT INTO scheme.room (apartment_id, color) VALUES (45, 'Purple');
INSERT INTO scheme.room (apartment_id, color) VALUES (2, 'Coral');
INSERT INTO scheme.room (apartment_id, color) VALUES (2, 'Salmon');
INSERT INTO scheme.room (apartment_id, color) VALUES (38, 'White');
INSERT INTO scheme.room (apartment_id, color) VALUES (19, 'Silver');


--
-- Name: tasks_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.tasks_id_seq', 1, false);


--
-- Name: apartments appartement_un; Type: CONSTRAINT; Schema: scheme; Owner: postgres
--

ALTER TABLE ONLY scheme.apartments
    ADD CONSTRAINT appartement_un UNIQUE (apartment_id, id);


--
-- Name: tasks tasks_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tasks
    ADD CONSTRAINT tasks_pkey PRIMARY KEY (id);


--
-- Name: apartments appartement_pk; Type: CONSTRAINT; Schema: scheme; Owner: postgres
--

ALTER TABLE ONLY scheme.apartments
    ADD CONSTRAINT appartement_pk PRIMARY KEY (apartment_id);


--
-- Name: human human_pk; Type: CONSTRAINT; Schema: scheme; Owner: postgres
--

ALTER TABLE ONLY scheme.human
    ADD CONSTRAINT human_pk PRIMARY KEY (id);


--
-- Name: human human_un; Type: CONSTRAINT; Schema: scheme; Owner: postgres
--

ALTER TABLE ONLY scheme.human
    ADD CONSTRAINT human_un UNIQUE (id);


--
-- Name: apartments appartement_fk; Type: FK CONSTRAINT; Schema: scheme; Owner: postgres
--

ALTER TABLE ONLY scheme.apartments
    ADD CONSTRAINT appartement_fk FOREIGN KEY (id) REFERENCES scheme.human(id);


--
-- Name: room room_fk; Type: FK CONSTRAINT; Schema: scheme; Owner: postgres
--

ALTER TABLE ONLY scheme.room
    ADD CONSTRAINT room_fk FOREIGN KEY (apartment_id) REFERENCES scheme.apartments(apartment_id);


--
-- PostgreSQL database dump complete
--

